version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"

  nginx:
    image: stock_recomentation_engine-frontend  # Usa la imagen generada para frontend
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Configuración personalizada
      - ./letsencrypt:/etc/letsencrypt                    # Certificados SSL
    depends_on:
      - frontend
      - backend1
      - backend2
      - backend3

  backend1:
    build: ./backend
    container_name: backend1
    ports:
      - "8000:8000"

  backend2:
    build: ./backend
    container_name: backend2
    ports:
      - "8001:8000"

  backend3:
    build: ./backend
    container_name: backend3
    ports:
      - "8002:8000"